---
# Default configuration values for My first Flask OAuth tool.
#
# This YAML file provides default settings for the Flask application. Rather
# than editing this file directly, create a file named 'config.yaml' in the
# same directory containing the keys and values that you wish to override.
#
# Some settings are commented out. These are used to show secret settings
# that MUST be provided in a 'config.yaml' file. Secret settings like
# password, OAuth tokens, and cryptographic seeds should never be commited to
# version control.
#
# See http://flask.pocoo.org/docs/0.12/config/ for other settings that may be
# useful.

# Name of the HTTP cookie that will be used to store session data. The Flask
# default value is 'session' which is likely to clash with other cookies on
# tools.wikimedia.org.
SESSION_COOKIE_NAME: mffot

# URL path for the session cookie. The Flask default is '/' which is not the
# best idea on Toolforge where multiple applications with different owners are
# hosted in the same domain. The value given here will only work if for the
# my-first-flask-oauth-tool account, so you should override it in your
# config.yaml if you have forked the tool for use with anohter account.
SESSION_COOKIE_PATH: /my-first-flask-oauth-tool

# Session cookies should only be sent over HTTPS secured connections
SESSION_COOKIE_SECURE: True

# Only send the cookie header to the client when its content changes
SESSION_REFRESH_EACH_REQUEST: False

# Generate https://... links by default
PREFERRED_URL_SCHEME: https

# Flask secret key. Used to create secure session cookies among other things.
# This should be a complex random value.
#SECRET_KEY:

# OAuth key and secret. These are generated for you by
# [[Special:OAuthConsumerRegistration/propose]]
#CONSUMER_KEY:
#CONSUMER_SECRET:

# Base URI to use when making OAuth requests to MediaWiki
OAUTH_MWURI: https://meta.wikimedia.org/w/index.php
